### ISSUE TITLE
All paths are relative to a specific machine 

### ISSUE THREAD

**Issue by VincenzoLaSpesa** [AzeezDa/Planets#1]
The project is impossible to build out of the box as all the library are referenced as full paths from a specific machine.

https://github.com/AzeezDa/Planets/blob/5a9723ed7da44c2dbeebac327fe1424096c60ceb/Planets.vcxproj#L91

like `C:\Users\Azeez\Desktop\Code\Own\Planets\include`

I suggest you to use something like vcpkg+cmake or at least to make the paths relative to the root folder of the solution.

**Comment by AzeezDa** [comment]
I apologise for the long wait. I finally had the time to learn CMake.
There is now a CMake file that builds the project. I tested it on both Windows (with Visual Studio 2022) and WSL2 (using XLaunch for displaying), and both built and ran successfully.
